In [ ]:
#建立list
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8 ,10]
a + b

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

In [1]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8 ,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [2]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[75, 97, 80, 56, 89]

In [3]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([99, 61, 60, 78, 51])

In [4]:
np.random.randint(50,high=100,size=(50, 5))

array([[90, 58, 74, 58, 72],
       [61, 53, 57, 76, 76],
       [60, 81, 61, 76, 82],
       [74, 86, 51, 65, 75],
       [95, 56, 50, 83, 61],
       [68, 58, 62, 97, 94],
       [94, 92, 83, 85, 51],
       [82, 98, 89, 51, 56],
       [58, 54, 69, 57, 93],
       [67, 77, 52, 91, 83],
       [57, 62, 69, 75, 69],
       [92, 99, 69, 57, 82],
       [77, 77, 88, 53, 51],
       [85, 50, 93, 59, 60],
       [79, 62, 55, 96, 51],
       [62, 91, 59, 75, 74],
       [93, 53, 59, 68, 57],
       [73, 98, 71, 59, 51],
       [87, 98, 95, 90, 50],
       [87, 58, 68, 99, 66],
       [51, 88, 92, 89, 71],
       [97, 94, 69, 69, 56],
       [79, 53, 54, 56, 92],
       [82, 72, 66, 81, 93],
       [61, 69, 79, 95, 92],
       [75, 66, 54, 99, 90],
       [85, 82, 86, 54, 55],
       [60, 93, 84, 64, 98],
       [93, 54, 50, 78, 56],
       [68, 57, 84, 63, 96],
       [98, 61, 68, 89, 76],
       [54, 78, 80, 91, 74],
       [70, 77, 96, 93, 84],
       [51, 72, 57, 63, 54],
       [66, 64